- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present


- name: Ensure nginx root directories exist
  ansible.builtin.file:
    path: "{{ nginx.static_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'


- name: Deploy nginx vhost for static files
  ansible.builtin.template:
    src: vhost_static.j2
    dest: /etc/nginx/sites-available/static.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx


- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/static.conf
    dest: /etc/nginx/sites-enabled/static.conf
    state: link
  notify: Reload nginx


- name: Remove default site if exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx


- name: Ensure nginx is enabled and running
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    